/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true
				if (controllerName=="aboutUs") return true
				if (controllerName=="activities") return true
				if (controllerName=="affiliatedPrograms") return true
				if (controllerName=="campingTrips") return true
				if (controllerName=="dayHikes") return true
				if (controllerName=="home") return true
				if (controllerName=="nightHikes") return true
				if (controllerName=="yogaHikes") return true
				if (controllerName=="photos") return true
				if (controllerName=="activity" && actionName=="full") return true
				
                // Access control by convention.
                accessControl()
            }
        }
    }
}
